# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mojito
email: oss@box.com
description: > # this means to ignore newlines until "baseurl:"
  An open sourced automation platform that enables continuous localization for software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opensource.box.com/mojito" # the base hostname & protocol for your site
mojito_green: <span><font color="green">mojito</font><span>
github_username:  mojito
# Build settings
markdown: kramdown
exclude: ["node_modules/", "webapp/"]
collections:
  docs:
    output: true
