package com.box.l10n.mojito.rest.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Configuration to trigger the export drop process.
 *
 * @author jaurambault
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ExportDropConfig {

  /**
   * Type of the translation kit to be created. Defines which content (text units) will be included
   * in the kit.
   *
   * @author jaurambault
   */
  public enum Type {

    /**
     * To create a kit for the translation process. it includes text units with filter {@link
     * StatusFilter#UNTRANSLATED_OR_TRANSLATION_NEEDED}
     */
    TRANSLATION,
    /**
     * To create a kit for the review process. It includes only text units with filter {@link
     * StatusFilter#REVIEW_NEEDED}
     */
    REVIEW
  };

  @JsonProperty(required = true)
  Long repositoryId;

  @JsonProperty("locales")
  List<String> bcp47Tags = new ArrayList<>();

  Date uploadTime;

  PollableTask pollableTask;

  Long dropId;

  Type type = Type.TRANSLATION;

  Boolean useInheritance = false;

  public Long getRepositoryId() {
    return repositoryId;
  }

  public void setRepositoryId(Long repositoryId) {
    this.repositoryId = repositoryId;
  }

  public Long getDropId() {
    return dropId;
  }

  public void setDropId(Long dropId) {
    this.dropId = dropId;
  }

  public List<String> getBcp47Tags() {
    return bcp47Tags;
  }

  public void setBcp47Tags(List<String> bcp47Tags) {
    this.bcp47Tags = bcp47Tags;
  }

  public Date getUploadTime() {

    if (uploadTime == null) {
      uploadTime = new Date();
    }

    return uploadTime;
  }

  public void setUploadTime(Date uploadTime) {
    this.uploadTime = uploadTime;
  }

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }

  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public Boolean getUseInheritance() {
    return useInheritance;
  }

  public void setUseInheritance(Boolean useInheritance) {
    this.useInheritance = useInheritance;
  }
}
