package com.box.l10n.mojito.rest.entity;

import com.box.l10n.mojito.okapi.FilterConfigIdOverride;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * @author jaurambault
 */
public class ImportLocalizedAssetBody {

  public enum StatusForEqualTarget {
    SKIPPED,
    REVIEW_NEEDED,
    TRANSLATION_NEEDED,
    APPROVED
  };

  String content;

  StatusForEqualTarget statusForEqualTarget;

  FilterConfigIdOverride filterConfigIdOverride;

  List<String> filterOptions;

  private PollableTask pollableTask;

  public ImportLocalizedAssetBody() {}

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public StatusForEqualTarget getStatusForEqualTarget() {
    return statusForEqualTarget;
  }

  public void setStatusForEqualTarget(StatusForEqualTarget statusForEqualTarget) {
    this.statusForEqualTarget = statusForEqualTarget;
  }

  public FilterConfigIdOverride getFilterConfigIdOverride() {
    return filterConfigIdOverride;
  }

  public void setFilterConfigIdOverride(FilterConfigIdOverride filterConfigIdOverride) {
    this.filterConfigIdOverride = filterConfigIdOverride;
  }

  public List<String> getFilterOptions() {
    return filterOptions;
  }

  public void setFilterOptions(List<String> filterOptions) {
    this.filterOptions = filterOptions;
  }

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }
}
