package com.box.l10n.mojito.rest.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 *
 * @author jaurambault
 */
public class ImportLocalizedAssetBody {

    public enum StatusForSourceEqTarget {
        SKIPPED,
        REVIEW_NEEDED,
        TRANSLATION_NEEDED,
        APPROVED
    };

    String content;

    StatusForSourceEqTarget statusSourceEqTarget;

    FilterConfigIdOverride filterConfigIdOverride;
        
    private PollableTask pollableTask;

    public ImportLocalizedAssetBody() {
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public StatusForSourceEqTarget getStatusSourceEqTarget() {
        return statusSourceEqTarget;
    }

    public void setStatusSourceEqTarget(StatusForSourceEqTarget statusSourceEqTarget) {
        this.statusSourceEqTarget = statusSourceEqTarget;
    }

    public FilterConfigIdOverride getFilterConfigIdOverride() {
        return filterConfigIdOverride;
    }

    public void setFilterConfigIdOverride(FilterConfigIdOverride filterConfigIdOverride) {
        this.filterConfigIdOverride = filterConfigIdOverride;
    }
    
    @JsonProperty
    public PollableTask getPollableTask() {
        return pollableTask;
    }

    /**
     * @JsonIgnore because this pollableTask is read only data generated by the
     * server side, it is not aimed to by external process via WS
     *
     * @param pollableTask
     */
    @JsonIgnore
    public void setPollableTask(PollableTask pollableTask) {
        this.pollableTask = pollableTask;
    }
}
