package com.box.l10n.mojito.rest.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public class RepositoryMachineTranslationBody {

  String repositoryName;
  List<String> targetBcp47tags;

  int sourceTextMaxCountPerLocale;

  PollableTask pollableTask;

  public String getRepositoryName() {
    return repositoryName;
  }

  public void setRepositoryName(String repositoryName) {
    this.repositoryName = repositoryName;
  }

  public List<String> getTargetBcp47tags() {
    return targetBcp47tags;
  }

  public void setTargetBcp47tags(List<String> targetBcp47tags) {
    this.targetBcp47tags = targetBcp47tags;
  }

  public int getSourceTextMaxCountPerLocale() {
    return sourceTextMaxCountPerLocale;
  }

  public void setSourceTextMaxCountPerLocale(int sourceTextMaxCountPerLocale) {
    this.sourceTextMaxCountPerLocale = sourceTextMaxCountPerLocale;
  }

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }
}
