ALTER TABLE QRTZ_BLOB_TRIGGERS MODIFY BLOB_DATA longblob;
ALTER TABLE QRTZ_TRIGGERS MODIFY JOB_DATA longblob;
ALTER TABLE QRTZ_JOB_DETAILS MODIFY JOB_DATA longblob;
ALTER TABLE QRTZ_CALENDARS MODIFY CALENDAR longblob;
