drop index UK__ASSET_INTEGRITY_CHECKER__REPOSITORY_ID__ASSET_EXTENSION on asset_integrity_checker;
create index I__ASSET_INTEGRITY_CHECKER__REPOSITORY_ID__ASSET_EXTENSION on asset_integrity_checker (repository_id, asset_extension);
