version: '2.4'
name: mojito
services:
  db:
    image: mysql:8.0.34
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 30s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: mojito
      MYSQL_USER: mojito
      MYSQL_PASSWORD: ChangeMe
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --max-connections=1000
      - --log_error_verbosity=2
    volumes:
        - mysql-data:/var/lib/mysql

  api:
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
#        limits:
#          cpus: '2'
#          memory: 1G
        reservations:
          cpus: '1'
          memory: 200M
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: docker/Dockerfile-bk17
      context: ../
    image: mojito:latest
    pull_policy: never
    links:
      - db
    ports:
      - "8080:8080"
      - "5005:5005" # debug port
    restart: always
    environment:
      JAVA_OPTS: '-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005'
      SPRING_APPLICATION_JSON: '{
      "spring.flyway.enabled": "true",
      "l10n.flyway.clean" : "false",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "none",
      "spring.datasource.url" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "spring.datasource.username" : "mojito",
      "spring.datasource.password" : "ChangeMe",
      "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.defer-datasource-initialization" : "false",
      "l10n.org.quartz.scheduler.enabled" : "false",
      "l10n.org.multi-quartz.enabled" : "true",
      "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.useProperties" : "true",
      "l10n.org.multi-quartz.schedulers.default.quartz.scheduler.instanceId" : "AUTO",
      "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.isClustered" : "true",
      "l10n.org.multi-quartz.schedulers.default.quartz.threadPool.threadCount" : 10,
      "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.class" : "org.quartz.impl.jdbcjobstore.JobStoreTX",
      "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.driverDelegateClass" : "org.quartz.impl.jdbcjobstore.StdJDBCDelegate",
      "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.dataSource" : "myDS",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.provider" : "hikaricp",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.driver" : "com.mysql.jdbc.Driver",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.URL" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.user" : "mojito",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.password" : "ChangeMe",
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.maxConnections" : 12,
      "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.validationQuery" : "select 1",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.useProperties" : "true",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.scheduler.instanceId" : "AUTO",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.isClustered" : "true",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.threadPool.threadCount" : 5,
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.class" : "org.quartz.impl.jdbcjobstore.JobStoreTX",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.driverDelegateClass" : "org.quartz.impl.jdbcjobstore.StdJDBCDelegate",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.dataSource" : "myDS",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.provider" : "hikaricp",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.driver" : "com.mysql.jdbc.Driver",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.URL" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.user" : "mojito",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.password" : "ChangeMe",
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.maxConnections" : 12,
      "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.validationQuery" : "select 1",
      "l10n.assetExtraction.quartz.schedulerName" : "lowPriority",
      "logging.level.com.box.l10n.mojito.quartz.QuartzPollableTaskScheduler" : "DEBUG",
      "logging.level.com.box.l10n.mojito.service.repository.statistics.RepositoryStatisticsJob" : "DEBUG",
      "logging.level.com.box.l10n.mojito.service.thirdparty.smartling.quartz" : "DEBUG"
      }'
  worker:
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      resources:
#        limits:
#          cpus: '2'
#          memory: 1G
        reservations:
          cpus: '1'
          memory: 200M
    depends_on:
      db:
        condition: service_healthy
    image: mojito:latest
    pull_policy: never
    links:
      - db
    restart: always
    ports:
      - "5005" # debug port (docker will provide a host port, retrieve it for a specific worker via `docker ps`)
    environment:
      JAVA_OPTS: '-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005'
      SPRING_APPLICATION_JSON: '{
        "spring.flyway.enabled": "true",
        "l10n.flyway.clean" : "false",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.datasource.url" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
        "spring.datasource.username" : "mojito",
        "spring.datasource.password" : "secret123",
        "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.defer-datasource-initialization" : "false",
        "l10n.org.quartz.scheduler.enabled" : "true",
        "l10n.org.multi-quartz.enabled" : "true",
        "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.useProperties" : "true",
        "l10n.org.multi-quartz.schedulers.default.quartz.scheduler.instanceId" : "AUTO",
        "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.isClustered" : "true",
        "l10n.org.multi-quartz.schedulers.default.quartz.threadPool.threadCount" : 10,
        "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.class" : "org.quartz.impl.jdbcjobstore.JobStoreTX",
        "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.driverDelegateClass" : "org.quartz.impl.jdbcjobstore.StdJDBCDelegate",
        "l10n.org.multi-quartz.schedulers.default.quartz.jobStore.dataSource" : "myDS",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.provider" : "hikaricp",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.driver" : "com.mysql.jdbc.Driver",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.URL" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.user" : "mojito",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.password" : "ChangeMe",
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.maxConnections" : 12,
        "l10n.org.multi-quartz.schedulers.default.quartz.dataSource.myDS.validationQuery" : "select 1",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.useProperties" : "true",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.scheduler.instanceId" : "AUTO",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.isClustered" : "true",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.threadPool.threadCount" : 5,
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.class" : "org.quartz.impl.jdbcjobstore.JobStoreTX",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.driverDelegateClass" : "org.quartz.impl.jdbcjobstore.StdJDBCDelegate",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.jobStore.dataSource" : "myDS",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.provider" : "hikaricp",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.driver" : "com.mysql.jdbc.Driver",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.URL" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.user" : "mojito",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.password" : "ChangeMe",
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.maxConnections" : 12,
        "l10n.org.multi-quartz.schedulers.lowPriority.quartz.dataSource.myDS.validationQuery" : "select 1",
        "l10n.assetExtraction.quartz.schedulerName" : "lowPriority",
        "logging.level.com.box.l10n.mojito.quartz.QuartzPollableTaskScheduler" : "DEBUG",
        "logging.level.com.box.l10n.mojito.service.repository.statistics.RepositoryStatisticsJob" : "DEBUG",
        "logging.level.com.box.l10n.mojito.service.thirdparty.smartling.quartz" : "DEBUG"
        }'

volumes:
  mysql-data: