package com.box.l10n.mojito.rest.drop;

import com.box.l10n.mojito.entity.PollableTask;
import com.box.l10n.mojito.service.drop.DropService;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Configuration to trigger the import drop process, see {@link
 * DropService#startDropImportProcess(Long, PollableTask)}
 *
 * @author aloison
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class CancelDropConfig {

  @JsonProperty(required = true)
  Long dropId;

  PollableTask pollableTask;

  public Long getDropId() {
    return dropId;
  }

  public void setDropId(Long dropId) {
    this.dropId = dropId;
  }

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }
}
