package com.box.l10n.mojito.rest.leveraging;

import com.box.l10n.mojito.entity.PollableTask;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Configuration to start the copy TM process
 *
 * @author jaurambault
 */
public class CopyTmConfig {

  Long sourceRepositoryId;
  Long targetRepositoryId;
  Long targetAssetId;
  Long sourceAssetId;
  String nameRegex;
  Map<Long, Long> sourceToTargetTmTextUnitIds;
  String targetBranchName;

  Mode mode = Mode.MD5;

  PreserveStatusMode preserveStatusMode = PreserveStatusMode.PRECISION;

  OverwriteMode overwriteMode = OverwriteMode.ALL;

  PollableTask pollableTask;

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }

  public Long getSourceRepositoryId() {
    return sourceRepositoryId;
  }

  public void setSourceRepositoryId(Long sourceRepositoryId) {
    this.sourceRepositoryId = sourceRepositoryId;
  }

  public Long getTargetRepositoryId() {
    return targetRepositoryId;
  }

  public void setTargetRepositoryId(Long targetRepositoryId) {
    this.targetRepositoryId = targetRepositoryId;
  }

  public Mode getMode() {
    return mode;
  }

  public void setMode(Mode mode) {
    this.mode = mode;
  }

  public String getNameRegex() {
    return nameRegex;
  }

  public void setNameRegex(String nameRegex) {
    this.nameRegex = nameRegex;
  }

  public Long getSourceAssetId() {
    return sourceAssetId;
  }

  public void setSourceAssetId(Long sourceAssetId) {
    this.sourceAssetId = sourceAssetId;
  }

  public Long getTargetAssetId() {
    return targetAssetId;
  }

  public void setTargetAssetId(Long targetAssetId) {
    this.targetAssetId = targetAssetId;
  }

  public Map<Long, Long> getSourceToTargetTmTextUnitIds() {
    return sourceToTargetTmTextUnitIds;
  }

  public void setSourceToTargetTmTextUnitIds(Map<Long, Long> sourceToTargetTmTextUnitIds) {
    this.sourceToTargetTmTextUnitIds = sourceToTargetTmTextUnitIds;
  }

  public String getTargetBranchName() {
    return targetBranchName;
  }

  public void setTargetBranchName(String targetBranchName) {
    this.targetBranchName = targetBranchName;
  }

  public PreserveStatusMode getPreserveStatusMode() {
    return preserveStatusMode;
  }

  public void setPreserveStatusMode(PreserveStatusMode preserveStatusMode) {
    this.preserveStatusMode = preserveStatusMode;
  }

  public OverwriteMode getOverwriteMode() {
    return overwriteMode;
  }

  public void setOverwriteMode(OverwriteMode overwriteMode) {
    this.overwriteMode = overwriteMode;
  }

  /** Matching mode for leveraging */
  public enum Mode {
    /** MD5 match means the message id, comment and content must be the same */
    MD5,
    /** Exact match means the content must be the same (message id and comment are not checked) */
    EXACT,
    /** Name match means the resource name must be the same (content and comment are not checked) */
    NAME,
    /** Copy based on a Map source to target tmTextUnitId */
    TUIDS
  }

  /**
   * Controls whether to keep the leveraged translation's status or downgrade it to
   * TRANSLATION_NEEDED.
   */
  public enum PreserveStatusMode {
    /**
     * Preserve status based on the match precision (ID, content). Lowest risk of carrying over
     * incorrect statuses.
     */
    PRECISION,
    /**
     * Preserve status when the match is unambiguous (single source text unit matched). Medium risk
     * — trusts all unique matches regardless of their precition.
     */
    UNIQUE,
    /**
     * Always preserve the source status. Highest risk — ambiguous matches may copy an arbitrarily
     * chosen translation at its original (possibly APPROVED) status.
     */
    ALL
  }

  /**
   * Controls when existing translations may be overwritten during leveraging, based on a comparison
   * of the candidate's effective status against the target locale's current status.
   *
   * <p>Status hierarchy (lowest to highest): TRANSLATION_NEEDED &lt; REVIEW_NEEDED &lt; APPROVED.
   */
  public enum OverwriteMode {
    /** Only leverage into locales that have no translation at all. */
    UNTRANSLATED_ONLY,
    /** Overwrite only when the candidate's effective status is strictly higher. */
    HIGHER_STATUS,
    /** Overwrite when the candidate's effective status is higher or equal. */
    HIGHER_OR_EQUAL_STATUS,
    /** Always overwrite regardless of the current status. */
    ALL
  }
}
