package com.box.l10n.mojito.rest.leveraging;

import com.box.l10n.mojito.entity.PollableTask;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Configuration to start the copy TM process
 *
 * @author jaurambault
 */
public class CopyTmConfig {

  Long sourceRepositoryId;
  Long targetRepositoryId;
  Long targetAssetId;
  Long sourceAssetId;
  String nameRegex;
  Map<Long, Long> sourceToTargetTmTextUnitIds;
  String targetBranchName;

  Mode mode = Mode.MD5;

  PreserveStatusMode preserveStatusMode = PreserveStatusMode.DEFAULT;

  TargetStatusFilter targetStatusFilter;

  PollableTask pollableTask;

  @JsonProperty
  public PollableTask getPollableTask() {
    return pollableTask;
  }

  /**
   * @JsonIgnore because this pollableTask is read only data generated by the server side, it is not
   * aimed to by external process via WS
   *
   * @param pollableTask
   */
  @JsonIgnore
  public void setPollableTask(PollableTask pollableTask) {
    this.pollableTask = pollableTask;
  }

  public Long getSourceRepositoryId() {
    return sourceRepositoryId;
  }

  public void setSourceRepositoryId(Long sourceRepositoryId) {
    this.sourceRepositoryId = sourceRepositoryId;
  }

  public Long getTargetRepositoryId() {
    return targetRepositoryId;
  }

  public void setTargetRepositoryId(Long targetRepositoryId) {
    this.targetRepositoryId = targetRepositoryId;
  }

  public Mode getMode() {
    return mode;
  }

  public void setMode(Mode mode) {
    this.mode = mode;
  }

  public String getNameRegex() {
    return nameRegex;
  }

  public void setNameRegex(String nameRegex) {
    this.nameRegex = nameRegex;
  }

  public Long getSourceAssetId() {
    return sourceAssetId;
  }

  public void setSourceAssetId(Long sourceAssetId) {
    this.sourceAssetId = sourceAssetId;
  }

  public Long getTargetAssetId() {
    return targetAssetId;
  }

  public void setTargetAssetId(Long targetAssetId) {
    this.targetAssetId = targetAssetId;
  }

  public Map<Long, Long> getSourceToTargetTmTextUnitIds() {
    return sourceToTargetTmTextUnitIds;
  }

  public void setSourceToTargetTmTextUnitIds(Map<Long, Long> sourceToTargetTmTextUnitIds) {
    this.sourceToTargetTmTextUnitIds = sourceToTargetTmTextUnitIds;
  }

  public String getTargetBranchName() {
    return targetBranchName;
  }

  public void setTargetBranchName(String targetBranchName) {
    this.targetBranchName = targetBranchName;
  }

  public PreserveStatusMode getPreserveStatusMode() {
    return preserveStatusMode;
  }

  public void setPreserveStatusMode(PreserveStatusMode preserveStatusMode) {
    this.preserveStatusMode = preserveStatusMode;
  }

  public TargetStatusFilter getTargetStatusFilter() {
    return targetStatusFilter;
  }

  public void setTargetStatusFilter(TargetStatusFilter targetStatusFilter) {
    this.targetStatusFilter = targetStatusFilter;
  }

  /** Matching mode for leveraging */
  public enum Mode {
    /** MD5 match means the message id, comment and content must be the same */
    MD5,
    /** Exact match means the content must be the same (message id and comment are not checked) */
    EXACT,
    /** Name match means the resource name must be the same (content and comment are not checked) */
    NAME,
    /** Copy based on a Map source to target tmTextUnitId */
    TUIDS
  }

  /** Controls whether the source translation's status is preserved during leveraging */
  public enum PreserveStatusMode {
    /** Default: the leverager decides based on match precision */
    DEFAULT,
    /** Preserve the source status only when the match is unique (single TMTextUnit matched) */
    UNIQUE,
    /** Always preserve the source status, even for non-unique matches */
    ANY
  }

  /**
   * Filters target text units by their current translation status before leveraging.
   *
   * <p>UNTRANSLATED selects text units with no translation in any locale. The other values
   * correspond to {@link com.box.l10n.mojito.entity.TMTextUnitVariant.Status} and select text units
   * that have at least one translation with the given status.
   */
  public enum TargetStatusFilter {
    UNTRANSLATED,
    APPROVED,
    REVIEW_NEEDED,
    TRANSLATION_NEEDED
  }
}
