name: Run JS tests - Ubuntu + Java 21

on:
  [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Spotless check
        run: mvn spotless:check
      - name: Maven install, test skipped
        run: mvn clean install -DskipTests
      - name: Npm test
        run: npm test
        working-directory: ./webapp